#!/usr/bin/env bash
# scripts/seed.sh -- one-line seed of the claude-api-contract template into a project folder.
#
# Collapses the multi-step "Quick start" block into a single command: clones the
# template (shallow) into a temp dir and copies all committed config + scaffolding
# files into the target folder, then wipes transient state the SessionStart hook
# regenerates.  Class B artifacts (spec/, examples/, openapi.yml) are NOT in the
# committed template and therefore NOT seeded -- /bootstrap creates them.
#
# After it finishes:
#   1) cd <TARGET>
#   2) (new project) git init && git add -A && git commit + gh repo create
#   3) bash scripts/setup-wsl.sh   (node/nvm + claude CLI; idempotent)
#   4) bash scripts/install.sh     (npm deps: TypeSpec, Spectral, Prism)
#   5) claude                      (launch Claude Code)
#   6) /doctor  ->  /bootstrap  ->  /preflight
#
# This script ONLY seeds files. It never runs git on the target, never pushes,
# never touches secrets, never runs npm.
#
# SUPPORTED: WSL2 Ubuntu (on Windows) and native Debian/Ubuntu/macOS bash.
# Windows PowerShell/cmd NOT supported (ADR 0001).
#
# Usage (one-liner from any empty folder):
#   bash <(curl -fsSL https://raw.githubusercontent.com/VadayI/claude-api-contract/main/scripts/seed.sh)
# or, if you already have the file:
#   bash scripts/seed.sh [TARGET_DIR] [--ref GIT_REF] [--url REPO_URL] [--force]
#
# Options:
#   TARGET_DIR     where to seed the config (default: current dir).
#   --ref GIT_REF  branch/tag to clone (default: main).
#   --url URL      clone from a fork instead of the canonical upstream.
#   --force        overwrite an already-seeded folder (.claude/ present).
#                  For upgrading an existing project prefer /update-from-template.
#
# Env override: CLAUDE_API_CONTRACT_URL takes precedence over the built-in URL.
set -euo pipefail

UPSTREAM_URL="${CLAUDE_API_CONTRACT_URL:-https://github.com/VadayI/claude-api-contract.git}"
REF=""
TARGET="."
FORCE=0

log()  { printf '\033[1;34m==>\033[0m %s\n' "$*"; }
ok()   { printf '\033[1;32m  ok\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m  !!\033[0m %s\n' "$*" >&2; }
die()  { printf '\033[1;31mFATAL\033[0m %s\n' "$*" >&2; exit 1; }
have() { command -v "$1" >/dev/null 2>&1; }

# --- 0. Parse args ------------------------------------------------------------
while [ $# -gt 0 ]; do
  case "$1" in
    --ref)   REF="${2:-}"; [ -n "$REF" ] || die "--ref needs a value"; shift 2 ;;
    --url)   UPSTREAM_URL="${2:-}"; [ -n "$UPSTREAM_URL" ] || die "--url needs a value"; shift 2 ;;
    --force) FORCE=1; shift ;;
    -h|--help) sed -n '2,35p' "$0" 2>/dev/null || true; exit 0 ;;
    -*)      die "unknown option: $1" ;;
    *)       TARGET="$1"; shift ;;
  esac
done

# --- 1. Platform + tool guards ------------------------------------------------
case "$(uname -s)" in
  Linux)  grep -qiE 'microsoft|wsl' /proc/version 2>/dev/null \
            && ok "running inside WSL2" \
            || warn "not WSL2 -- assuming native Linux. Continuing." ;;
  Darwin) ok "running on macOS (native bash)" ;;
  *)      die "Unsupported platform '$(uname -s)'. On Windows install WSL2 Ubuntu and run this from inside it (docs/decisions/0001-drop-windows-native-shell.md)." ;;
esac
have git || die "git not found. Install it first (WSL2: sudo apt install -y git)."

# --- 2. Resolve + guard the target -------------------------------------------
mkdir -p "$TARGET"
TARGET="$(cd "$TARGET" && pwd)"
log "Seeding claude-api-contract template into: $TARGET"

if [ -e "$TARGET/.claude" ] && [ "$FORCE" -ne 1 ]; then
  die "$TARGET already has .claude/ (looks seeded). Re-run with --force to overwrite, or use /update-from-template to upgrade an existing project (preserves your edits)."
fi

# --- 3. Clone to a temp dir (cleaned on exit) ---------------------------------
CLONE="$(mktemp -d)"
cleanup() { rm -rf "$CLONE"; }
trap cleanup EXIT

REF_ARG="${REF:-main}"
log "Cloning $UPSTREAM_URL @ $REF_ARG"
git clone --quiet --depth 1 --branch "$REF_ARG" "$UPSTREAM_URL" "$CLONE" \
  || die "clone failed (bad --ref '$REF_ARG' or unreachable URL?)"
ok "cloned"

# --- 4. Copy the full committed template (Class B artifacts are not in git) ---
# The committed template on main deliberately excludes spec/, examples/,
# openapi.yml (Class B -- scaffolded by /bootstrap).  A shallow clone therefore
# gives exactly the right file set; we copy everything except .git/.
log "Copying template files"
find "$CLONE" -mindepth 1 -maxdepth 1 ! -name '.git' | while IFS= read -r item; do
  name="$(basename "$item")"
  if [ -d "$item" ]; then
    # copy CONTENTS into the target dir: overwrites template files without
    # nesting ($TARGET/$name/$name) when the dir already exists (--force),
    # and never deletes unrelated user files. GNU + BSD cp compatible.
    mkdir -p "$TARGET/$name"
    cp -r "$item/." "$TARGET/$name/"
  else
    cp "$item" "$TARGET/$name"
  fi
done
ok "copied"

# --- 5. Wipe transient state (regenerated by the SessionStart hook) -----------
rm -f "$TARGET/.claude/memory/env-detect.json" \
      "$TARGET/.claude/memory/command-log.jsonl"
ok "wiped transient memory"

# --- 6. Runner check + next steps --------------------------------------------
echo
claude_path="$(command -v claude || true)"
case "$claude_path" in
  /mnt/c/*|*.exe)
    warn "'claude' resolves to the Windows binary ($claude_path). Install the WSL2-native CLI: bash scripts/setup-wsl.sh" ;;
  "")
    warn "'claude' not on PATH yet. Install it: bash scripts/setup-wsl.sh (then open a new shell)." ;;
  *)
    ok "'claude' resolves to a Linux path: $claude_path" ;;
esac

echo
log "Seeded. Next steps:"
echo "  1) cd $TARGET"
echo "  2) (new project) git init && git add -A && git commit -m 'init: bootstrap from claude-api-contract template'"
echo "     gh repo create <name> --private --source=. --push"
echo "  3) (first time on this machine) bash scripts/setup-wsl.sh   # node (nvm) + claude + gh"
echo "  4) bash scripts/install.sh                                   # npm deps (TypeSpec, Spectral, Prism)"
echo "  5) claude"
echo "  6) in the session:  /doctor  ->  /bootstrap  ->  /preflight"
